Map<String, dynamic> buildSeed() {
  final now = DateTime.now().toIso8601String();
  String iso(Duration ago) =>
      DateTime.now().subtract(ago).toIso8601String();

  return {
    'admin_credentials': {
      'login': 'admin@santex.local',
      'password': 'Admin123!',
    },
    'categories': [
      {
        'id': 'cat-kran',
        'name': 'Kranlar',
        'code': 'kran',
        'description': 'Oshxona va hammom kranlari',
        'icon': 'water_drop',
        'created_at': iso(const Duration(days: 90)),
      },
      {
        'id': 'cat-dush',
        'name': 'Dush',
        'code': 'dush',
        'description': 'Dush kabina va tizimlari',
        'icon': 'shower',
        'created_at': iso(const Duration(days: 90)),
      },
      {
        'id': 'cat-unitaz',
        'name': 'Unitaz',
        'code': 'unitaz',
        'description': 'Sanuzel jihozlari',
        'icon': 'wc',
        'created_at': iso(const Duration(days: 90)),
      },
      {
        'id': 'cat-truba',
        'name': 'Trubalar',
        'code': 'truba',
        'description': 'PP-R va metal plastik',
        'icon': 'plumbing',
        'created_at': iso(const Duration(days: 90)),
      },
      {
        'id': 'cat-nasos',
        'name': 'Nasoslar',
        'code': 'nasos',
        'description': 'Bosim va suv nasoslari',
        'icon': 'settings_input_component',
        'created_at': iso(const Duration(days: 90)),
      },
    ],
    'products': [
      _p('prd-001', 'Grohe Essence Kran', 'cat-kran', 450000, 25, 'KR-001',
          oldPrice: 520000, badge: 'chegirma', sold: 42, days: 40),
      _p('prd-002', 'Hansgrohe Focus Kran', 'cat-kran', 680000, 15, 'KR-002',
          badge: 'ommabop', sold: 35, days: 25),
      _p('prd-003', 'Iddis Premio Kran', 'cat-kran', 280000, 40, 'KR-003',
          sold: 28, days: 18),
      _p('prd-004', 'Roca Esla Kran', 'cat-kran', 320000, 8, 'KR-004',
          badge: 'yangi', sold: 12, days: 7),
      _p('prd-005', 'Aquaform 90x90 Dush Kabina', 'cat-dush', 1850000, 6,
          'DK-001', oldPrice: 2100000, badge: 'chegirma', sold: 15, days: 35),
      _p('prd-006', 'Ravak Chrome Dush Kabina', 'cat-dush', 2400000, 4,
          'DK-002', badge: 'tavsiya', sold: 10, days: 32),
      _p('prd-007', 'Dush To\'plami Rain', 'cat-dush', 560000, 20, 'DK-003',
          sold: 30, days: 20),
      _p('prd-008', 'Cersanit Mito Unitaz', 'cat-unitaz', 780000, 18, 'UN-001',
          badge: 'ommabop', sold: 55, days: 50),
      _p('prd-009', 'Roca Meridian Unitaz', 'cat-unitaz', 1200000, 9, 'UN-002',
          oldPrice: 1400000, badge: 'chegirma', sold: 22, days: 45),
      _p('prd-010', 'Laufen Pro Unitaz', 'cat-unitaz', 1650000, 5, 'UN-003',
          badge: 'tavsiya', sold: 18, days: 42),
      _p('prd-011', 'Gigant Sifon', 'cat-unitaz', 85000, 60, 'UN-004',
          sold: 95, days: 60),
      _p('prd-012', 'PP-R Truba 20mm', 'cat-truba', 12000, 500, 'TR-001',
          sold: 320, days: 120),
      _p('prd-013', 'PP-R Truba 32mm', 'cat-truba', 18000, 350, 'TR-002',
          sold: 210, days: 110),
      _p('prd-014', 'Metal Plastik Truba 16mm', 'cat-truba', 22000, 200,
          'TR-003', sold: 180, days: 100),
      _p('prd-015', 'Grundfos CM3 Nasos', 'cat-nasos', 2800000, 7, 'NS-001',
          badge: 'tavsiya', sold: 12, days: 70),
      _p('prd-016', 'Wilo Sub TWI 4 Nasos', 'cat-nasos', 3600000, 3, 'NS-002',
          sold: 8, days: 65),
      _p('prd-017', 'DAB Aquajet 132M', 'cat-nasos', 1900000, 2, 'NS-003',
          oldPrice: 2200000, badge: 'chegirma', sold: 14, days: 55),
    ],
    'drivers': [
      {
        'id': 'drv-ali',
        'name': 'Ali Karimov',
        'phone': '+998901234567',
        'login': 'driver_ali',
        'password': 'Driver123!',
        'vehicle_number': '01 A 123 BB',
        'status': 'free',
        'completed_orders': 47,
        'rating': 4.8,
        'current_order_id': null,
      },
      {
        'id': 'drv-bobur',
        'name': 'Bobur Toshmatov',
        'phone': '+998901234568',
        'login': 'driver_bobur',
        'password': 'Driver123!',
        'vehicle_number': '10 B 456 CC',
        'status': 'busy',
        'completed_orders': 35,
        'rating': 4.6,
        'current_order_id': 'ORD-1002',
      },
      {
        'id': 'drv-jasur',
        'name': 'Jasur Nazarov',
        'phone': '+998901234569',
        'login': 'driver_jasur',
        'password': 'Driver123!',
        'vehicle_number': '30 C 789 DD',
        'status': 'offline',
        'completed_orders': 28,
        'rating': 4.9,
        'current_order_id': null,
      },
    ],
    'orders': [
      _o('ORD-1001', 'Sardor Yusupov', '+998901111111',
          'Toshkent, Yunusobod 3-kvartal, 15-uy',
          [_oi('prd-001', 'Grohe Essence Kran', 2, 450000)],
          900000, 'completed', 5, 'drv-ali', 41.3389, 69.3456,
          email: 'sardor@mail.com'),
      _o('ORD-1002', 'Malika Rahimova', '+998902222222',
          'Toshkent, Chilonzor 9-kvartal, 22-uy',
          [_oi('prd-005', 'Aquaform 90x90 Dush Kabina', 1, 1850000)],
          1850000, 'processing', 0, 'drv-bobur', 41.2922, 69.2000,
          email: 'malika@mail.com', hours: 3),
      _o('ORD-1003', 'Dilshod Mirzayev', '+998903333333',
          'Toshkent, Mirzo Ulugbek, Qorasaroy 5-uy',
          [
            _oi('prd-008', 'Cersanit Mito Unitaz', 1, 780000),
            _oi('prd-011', 'Gigant Sifon', 2, 85000),
          ],
          950000, 'pending', 0, null, 41.35, 69.38, hours: 1),
      _o('ORD-1004', 'Gulnora Ergasheva', '+998904444444',
          'Samarqand, Registon ko\'chasi, 8-uy',
          [_oi('prd-012', 'PP-R Truba 20mm', 10, 12000)],
          120000, 'pending', 0, null, 39.6547, 66.9758, minutes: 30),
      _o('ORD-1005', 'Sherzod Qodirov', '+998905555555',
          'Toshkent, Shayxontohur, Navro\'z 3-uy',
          [_oi('prd-015', 'Grundfos CM3 Nasos', 1, 2800000)],
          2800000, 'cancelled', 2, null, 41.31, 69.28),
    ],
    'applications': [
      {
        'id': 'APP-001',
        'customer_name': 'Sardor Yusupov',
        'phone': '+998901111111',
        'email': 'sardor@mail.com',
        'bonus_type': '5% chegirma',
        'points': 50,
        'current_balance': 65,
        'status': 'newRequest',
        'created_at': iso(const Duration(days: 1)),
        'admin_note': null,
      },
      {
        'id': 'APP-002',
        'customer_name': 'Malika Rahimova',
        'phone': '+998902222222',
        'email': null,
        'bonus_type': 'Bepul yetkazib berish',
        'points': 30,
        'current_balance': 42,
        'status': 'reviewing',
        'created_at': iso(const Duration(hours: 5)),
        'admin_note': null,
      },
    ],
    'created_at': now,
  };
}

Map<String, dynamic> _p(
  String id,
  String name,
  String catId,
  num price,
  int stock,
  String sku, {
  num? oldPrice,
  String badge = 'none',
  int sold = 0,
  int days = 30,
}) => {
  'id': id,
  'name': name,
  'category_id': catId,
  'price': price,
  'old_price': oldPrice,
  'stock': stock,
  'sku': sku,
  'description': '',
  'badge': badge,
  'created_at': DateTime.now()
      .subtract(Duration(days: days))
      .toIso8601String(),
  'sold_count': sold,
};

Map<String, dynamic> _o(
  String id,
  String customer,
  String phone,
  String address,
  List<Map<String, dynamic>> items,
  num total,
  String status,
  int days,
  String? driverId,
  double lat,
  double lng, {
  String? email,
  int hours = 0,
  int minutes = 0,
}) => {
  'id': id,
  'customer_name': customer,
  'phone': phone,
  'email': email,
  'address': address,
  'items': items,
  'total': total,
  'status': status,
  'created_at': DateTime.now()
      .subtract(Duration(days: days, hours: hours, minutes: minutes))
      .toIso8601String(),
  'driver_id': driverId,
  'latitude': lat,
  'longitude': lng,
};

Map<String, dynamic> _oi(String pid, String name, int qty, num price) => {
  'product_id': pid,
  'name': name,
  'quantity': qty,
  'price': price,
};
